### PR TITLE
Fix macOS build

### PR DESCRIPTION
**Pull request by zoq**
On macOS the OpenCL header are located in `OpenCL/` instead of `CL/`.

Signed-off-by: Marcus Edel <marcus.edel@collabora.com>

### CODE REVIEW

**Comment by boxerab** [comment]
Thank you, zoq!

**Comment by boxerab** [comment]
I see you removed a few CL error codes : were these not compiling on osx ?

**Comment by zoq** [comment]
> I see you removed a few CL error codes : were these not compiling on osx ?

Ahh sorry, wasn't my plan to include them. But yeah some of the code break the build. Do you want me to revert, or are you going to just reinclude them?

**Comment by boxerab** [comment]
thanks I will #ifdef them away - these are 1.2 and 2.x error codes

**Comment by zoq** [comment]
Thanks!

**Pull request merged**
